version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/network-lab
hooks:
  AfterInstall:
    - location: scripts/deploy-topology.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy-configs.sh
      timeout: 600
      runas: ubuntu
